### ISSUE TITLE
Create a Post page

### ISSUE THREAD

**Issue by deepakrajkranti** [deepakrajkranti/CarrerHub#3]
Create a post page that should be routed with path: "/post/:{post_id}"

**Comment by deepakrajkranti** [comment]
@Divyanshau2001  I have assigned this issue to you

**Comment by Divyanshau2001** [comment]
@deepakrajkranti  working on it.

**Comment by deepakrajkranti** [comment]
@Divyanshau2001 I've made the content length change, so you can create a full post and check if it's working on your page.

**Comment by Divyanshau2001** [comment]
@deepakrajkranti  Text change is not reflecting in UI.
